spring:
  application:
    name: Booking Tour & Hotel
  servlet:
    multipart:
      max-file-size: 5MB
  profiles:
    active: dev
  data:
    redis:
      port: 6379
      host: localhost
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  security:
    user:
      name: username
    oauth2:
      client:
        registration:
          google:
            client-secret: ${CLIENT_SECRET}
            client-id: ${CLIENT_ID}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# port
server:
  port: 8080
#prefix endpoint
  servlet:
    context-path: /api/
